FROM node:20-alpine3.18

RUN apk add g++ make py3-pip

WORKDIR /app/

COPY ./ /app/
RUN apk add --no-cache git
RUN npm install -g npm@10.3.0
RUN npm install -g node-gyp
RUN npm upgrade --save --legacy-peer-deps
RUN npm install

# RUN yarn install
# RUN yarn run build
# RUN yarn run start
