version: "3.9"

services:
  db:
    image: postgres:13
    hostname: db
    env_file:
      - ./.env
    networks:
      - db_network
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    restart: always

networks:
  db_network:
    driver: bridge
    external: true
volumes:
  db_data:
