version: "3.9"

services:
  # Proxyサーバーを経由するのでウォレットサーバーにおけるWebサーバーは不要
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - "3001:3000"
    networks:
      - db_network
    container_name: chilowallet
    restart: "always"
    environment:
      - LOG_LEVEL=$LOG_LEVEL
    logging:
      driver: json-file
      options:
        max-size: ${LOG_MAX_SIZE}
        max-file: ${LOG_MAX_FILE}

networks:
  db_network:
    driver: bridge
    external: true
