openapi: 3.0.3
info:
  title: Portal Badges API
  description: 教員研修システム向けバッジ関連データ取得API
  version: 0.9.2
servers:
  - url: https://chiloportal.example.com/api/v1
tags:
  - name: consumer
    description: コンシューマ情報取得
  - name: consumer list
    description: コンシューマ情報一覧
  - name: target occupations category list
    description: 受講対象に関連するカテゴリ一覧
  - name: target carrier stage category list
    description: 受講レベルに関連するカテゴリ一覧
  - name: portal category list
    description: ポータルカテゴリ一覧
  - name: categorised badge
    description: カテゴライズドバッジ情報取得
  - name: target occupations
    description: 受講対象取得
  - name: target carrier stage list
    description: 受講対象に関連する受講レベル一覧
  - name: keyword find
    description: バッジ検索（すべて）
  - name: keyword find target occupations
    description: バッジ検索（受講対象）
  - name: keyword find target carrier stage
    description: バッジ検索（受講レベル）
  - name: keyword find badges
    description: バッジ検索（バッジ名称）
  - name: badges
    description: バッジ情報取得
  - name: wisdom badges list
    description: 能力バッジ一覧取得
  - name: badges consumer list
    description: バッジを承認しているコンシューマの一覧
  - name: badges criteria list
    description: バッジの研修内容一覧取得
  - name: consumer target occupations list
    description: 指定したコンシューマIDの受講対象一覧
paths:
  /consumer:
    get:
      tags:
        - consumer
      description: 指定されたコンシューマIDに該当するコンシューマ情報を返却します
      operationId: findConsumer
      parameters:
        - name: consumer_id
          in: query
          description: consumer id
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Consumer'
        '400':
          description: Invalid ID supplied
        '404':
          description: Consumer not found
        '405':
          description: Validation exception
  /consumer/list:
    get:
      tags:
        - consumer list
      description: 登録されているコンシューマ情報を一覧で返却します
      operationId: findConsumerList
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Consumer'
        '404':
          description: Consumer not found
  /targetOccupations/category/list:
    get:
      tags:
        - target occupations category list
      description: 指定された受講対象IDに関連するカテゴリ情報を一覧で返却します
      operationId: findCategoryList
      parameters:
        - name: target_occupations_id
          in: query
          description: target occupations id
          required: true
          schema:
            type: number
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
        '400':
          description: Invalid ID supplied
        '404':
          description: not found
        '405':
          description: Validation exception
  /targetCarrierStage/category/list:
    get:
      tags:
        - target carrier stage category list
      description: 指定された受講レベルIDに関連するカテゴリ情報を返却します
      operationId: findCategory
      parameters:
        - name: target_carrier_stage_id
          in: query
          description: target carrier stage id
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    category:
                      $ref: '#/components/schemas/Category'
                    wisdom_badges:
                      type: integer
                      format: int64
                      example: 101
        '400':
          description: Invalid ID supplied
        '404':
          description: Data not found
        '405':
          description: Validation exception
  /portalCategory/list:
    get:
      tags:
        - portal category list
      description: 登録されているポータルカテゴリ情報を一覧で返却します
      operationId: findPortalCategoryList
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PortalCategory'
        '400':
          description: Invalid ID supplied
        '404':
          description: Data not found
        '405':
          description: Validation exception
  /categorisedBadge:
    get:
      tags:
        - categorised badge
      description: 指定されたカテゴリIDに該当するカテゴライズドバッジ情報を返却します
      operationId: findCategorisedbadge
      parameters:
        - name: category_id
          in: query
          description: category id
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CategorisedBadge'
        '400':
          description: Invalid ID supplied
        '404':
          description: Category not found
        '405':
          description: Validation exception
  /targetOccupations:
    get:
      tags:
        - target occupations
      description: 指定された受講対象IDに該当する受講対象情報を返却します
      operationId: findTargetOccupations
      parameters:
        - name: target_occupations_id
          in: query
          description: target occupations id
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Target_Occupations'
        '400':
          description: Invalid ID supplied
        '404':
          description: Target occupations not found
        '405':
          description: Validation exception
  /targetCarrierStage/list:
    get:
      tags:
        - target carrier stage list
      description: 指定された受講対象IDに関連する受講レベル情報を返却します
      operationId: findTargetCarrierStage
      parameters:
        - name: target_occupations_id
          in: query
          description: target occupations id
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Target_Carrier_Stage'
        '400':
          description: Invalid ID supplied
        '404':
          description: Data not found
        '405':
          description: Validation exception
  /find:
    get:
      tags:
        - keyword find
      description: 指定されたキーワードに関連する受講対象/受講レベル/バッジ情報のすべてからバッジ情報を返却します
      operationId: findKeywordAll
      parameters:
        - name: keyword
          in: query
          description: keyword
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CategorisedBadgeDetail'
        '400':
          description: Invalid keyword supplied
        '404':
          description: Data not found
        '405':
          description: Validation exception
  /find/targetOccupations:
    get:
      tags:
        - keyword find target occupations
      description: 指定されたキーワードに関連する受講対象のバッジ情報を返却します
      operationId: findKeywordTargetOccupations
      parameters:
        - name: keyword
          in: query
          description: keyword
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CategorisedBadgeDetail'
        '400':
          description: Invalid keyword supplied
        '404':
          description: Data not found
        '405':
          description: Validation exception
  /find/targetCarrierStage:
    get:
      tags:
        - keyword find target carrier stage
      description: 指定されたキーワードに関連する受講レベルのバッジ情報を返却します
      operationId: findKeywordTargetCarrierStage
      parameters:
        - name: keyword
          in: query
          description: keyword
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CategorisedBadgeDetail'
        '400':
          description: Invalid keyword supplied
        '404':
          description: Data not found
        '405':
          description: Validation exception
  /find/badges:
    get:
      tags:
        - keyword find badges
      description: 指定されたキーワードに関連するバッジのバッジ情報を返却します
      operationId: findKeywordBadges
      parameters:
        - name: keyword
          in: query
          description: keyword
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CategorisedBadgeDetail'
        '400':
          description: Invalid keyword supplied
        '404':
          description: Data not found
        '405':
          description: Validation exception
  /badges:
    get:
      tags:
        - badges
      description: 指定されたバッジIDのバッジ関連情報を返却します
      operationId: findBadges
      parameters:
        - name: badges_id
          in: query
          description: badges id
          required: true
          schema:
            type: number
        - name: badges_type
          in: query
          description: badges type
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadgeDetail'
        '400':
          description: Invalid ID supplied
        '404':
          description: Badges not found
        '405':
          description: Validation exception
  /wisdomBadges/list:
    get:
      tags:
        - wisdom badges list
      description: 能力バッジ一覧を返却します
      operationId: Badges
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Badges'
        '404':
          description: Badges not found
  /badges/consumer/list:
    get:
      tags:
        - badges consumer list
      description: 指定されたバッジIDに関連するコンシューマのリストを返却します
      operationId: findBadgesConsumer
      parameters:
        - name: badges_id
          in: query
          description: Badges id
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Consumer'
        '400':
          description: Invalid ID supplied
        '404':
          description: Badges not found
        '405':
          description: Validation exception
  /badges/criteria/list:
    get:
      tags:
        - badges criteria list
      description: 指定された知識バッジIDに関連する研修内容のリストを返却します
      operationId: findBadgesCriteria
      parameters:
        - name: badges_id
          in: query
          description: Badges id
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Criteria'
        '400':
          description: Invalid ID supplied
        '404':
          description: Knowledge Badges not found
        '405':
          description: Validation exception
  /consumer/targetOccupations/list:
    get:
      tags:
        - consumer target occupations list
      description: 指定されたコンシューマIDに関連する受講対象リストを返却します
      operationId: TargetOccupationsList
      parameters:
        - name: consumer_id
          in: query
          description: consumer id
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Target_Occupations'
        '400':
          description: Invalid keyword supplied
        '404':
          description: Data not found
        '405':
          description: Validation exception

components:
  schemas:
    Consumer:
      type: object
      properties:
        consumer_id:
          type: integer
          format: int64
          example: 101
        name:
          type: string
          example: consumer101
        url:
          type: string
          example: https://example.com/consumer101/
        email:
          type: string
          example: consumer101@example.com
    Category:
      type: object
      properties:
        category1:
          type: array
          items:
            $ref: '#/components/schemas/Category1'
    Category1:
      type: object
      properties:
        category1_name:
          type: string
          example: category1011
        category2:
          type: array
          items:
            $ref: '#/components/schemas/Category2'
    Category2:
      properties:
        category2_name:
          type: string
          example: category1012
        category3:
          type: array
          items:
            $ref: '#/components/schemas/Category3'
    Category3:
      properties:
        category_id:
          type: integer
          format: int64
          example: 101123
        category3_name:
          type: string
          example: category1013
    PortalCategory:
      type: object
      properties:
        portal_category_id:
          type: integer
          format: int64
          example: 101
        name:
          type: string
          example: portalCategory101
        description:
          type: string
          example: PortalCategory101 description...
        badges_count:
          type: integer
          example: 5
    CategorisedBadge:
      type: object
      properties:
        badges_id:
          type: integer
          format: int64
          example: 101
        cell_id:
          type: integer
          format: int64
          example: 101
        description:
          type: string
          example: categorised badges description...
    CategorisedBadgeDetail:
      type: object
      properties:
        category:
          type: object
          items:
            $ref: '#/components/schemas/Category'
        consumer:
          type: object
          items:
            $ref: '#/components/schemas/Consumer'
        badge:
          type: object
          items:
            $ref: '#/components/schemas/BadgeDetail'
        target_occupations:
          type: object
          items:
            $ref: '#/components/schemas/Target_Occupations'
        target_carrier_stage:
          type: object
          items:
            $ref: '#/components/schemas/Target_Carrier_Stage'
        description:
          type: string
          example: categorised badges description...
    Target_Occupations:
      type: object
      properties:
        target_occupations_id:
          type: integer
          format: int64
          example: 101
        name:
          type: string
          example: targetOccupations101
        description:
          type: string
          example: TargetOccupations101 description...
    Target_Carrier_Stage:
      type: object
      properties:
        target_carrier_stage_id:
          type: integer
          format: int64
          example: 101
        name:
          type: string
          example: targetCarrierStage101
        description:
          type: string
          example: targetCarrierStage101 description...
    Criteria:
      type: object
      properties:
        criteria_id:
          type: integer
          format: int64
          example: 101
        type:
          type: string
          example: criteria_type101
        name:
          type: string
          example: criteria_name101
    Badges:
      type: object
      properties:
        badges_id:
          type: integer
          format: int64
          example: 101
        name:
          type: string
          example: degitalbadge101
        image:
          type: string
          example: degitalbadge101.jpg
        knowledge_badges_count:
          type: integer
          example: 7
    BadgeList:
      type: integer
      format: int64
      example: 101
    BadgeDetail:
      type: object
      properties:
        badges_id:
          type: integer
          format: int64
          example: 101
        type:
          type: string
          enum:
            - knowledge
            - wisdom
        name:
          type: string
          example: degitalbadge101
        description:
          type: string
          example: degitalbadge101_description
        image:
          type: string
          example: degitalbadge101.jpg
        degital_badge_class_id:
          type: string
          example: degitalbadge_classID
        detail:
          oneOf:
            - $ref: '#/components/schemas/knowledge'
            - $ref: '#/components/schemas/wisdom'
        url:
          type: string
          example: https://example/knowledge/url/sample
    wisdom:
      type: object
      properties:
        knowledge_badges_list:
          type: array
          items:
            $ref: '#/components/schemas/BadgeList'
    knowledge:
      type: array
      items:
        $ref: '#/components/schemas/Criteria'
