name: backend CD

on:
  push:
    branches:
      - develop
    paths-ignore:
      - "frontend/**"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SECRET_KEY }}
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          port: ${{secrets.SSH_PORT}}
          script: |
            rm -rf /tmp/chiloportal
            git clone https://github.com/npocccties/chiloportal.git /tmp/chiloportal
            cp /tmp/chiloportal/backend/deploy.sh /opt
            cd /opt
            chmod 755 deploy.sh
            ./deploy.sh
