name: Django CI

on:
  pull_request:
    paths-ignore:
      - "frontend/**"
defaults:
  run:
    working-directory: backend
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build docker containers
      run: |
        cp .env.localhost .env
        cp docker-compose.github.yml docker-compose.yml
        docker-compose up -d
    - name: Run tests 
      run: |
        docker-compose ps
        docker-compose exec -T app python /workspace/manage.py test --exclude-tag=fuzzing
        
