name: backend CI

on:
  pull_request:
    paths:
      - 'backend/**'
      - '!backend/README.md'
      - '!backend/LICENSE'
defaults:
  run:
    working-directory: backend
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build docker containers
      run: |
        cp .env.localhost .env
        cp docker-compose.localhost.yml docker-compose.yml
        docker-compose up -d
    - name: Run tests 
      run: |
        docker-compose ps
        docker-compose exec -T app python /workspace/manage.py test --exclude-tag=fuzzing

