name: CD

on:
  push:
    branches:
      - develop
    paths:
      - 'frontend/**'
      - 'backend/**'
      - '!backend/README.md'
      - '!backend/LICENSE'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SECRET_KEY }}
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          port: ${{secrets.SSH_PORT}}
          script: |
            cd /opt
            sudo git clone https://github.com/npocccties/chiloportal.git >& /dev/null
            # sudo cp .env.manual-ssl-certs chiloportal/backend/.env
            sudo cp chiloportal/backend/.env.dev-server chiloportal/backend/.env
            cd chiloportal
            sudo chmod 755 deploy.sh
            ./deploy.sh
