on:
  pull_request:
    paths:
      - "frontend/**"
      - "backend/doc/openapi.yaml"
defaults:
  run:
    working-directory: frontend
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v4
        with:
          node-version-file: "frontend/package.json"
          cache: "yarn"
          cache-dependency-path: "frontend/yarn.lock"
        env:
          SKIP_YARN_COREPACK_CHECK: true
      - run: corepack enable
      - run: yarn install --immutable
      - run: yarn lint
      - run: yarn test
      - id: format
        continue-on-error: true
        run: |
          yarn format
          echo "status=$(git status --porcelain)" >> $GITHUB_OUTPUT
      - if: steps.format.outputs.status != ''
        run: |
          git -c "user.name=github-actions[bot]" -c "user.email=github-actions[bot]@users.noreply.github.com" commit -a -m "bot: format"
          git push origin HEAD
      - run: cp .env.development .env
      - run: docker build -t frontend -f ../Dockerfile.frontend ..
