on:
  pull_request:
    paths-ignore:
      - "backend/**"
defaults:
  run:
    working-directory: frontend
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
          cache-dependency-path: "frontend/yarn.lock"
      - run: yarn install --check-files --frozen-lockfile --non-interactive
      - run: yarn lint
      - id: format
        continue-on-error: true
        run: |
          yarn format
          echo "::set-output name=status::$(git status --porcelain)"
      - if: steps.format.outputs.status != ''
        run: |
          git -c "user.name=github-actions[bot]" -c "user.email=github-actions[bot]@users.noreply.github.com" comit -a -m "bot: format"
      - run: yarn build
